### ISSUE TITLE
Sugestão de ação

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [project-portable/silver-spork#4]
### Qual o nome que deve ser exibido no Whisker Menu?

dfdfdf

### Qual comando ou site?

sdsdsd

### Qual padrão o usuário deve digitar?

sdfsdf

### Tipo

Executar um comando

### Termo de bom senso

- [X] Sim, não eustou

**Comment by sudo-give-me-coffee** [comment]
@daigoasuka irá verificar, se tudo estiver ok, ele irá criar um arquivo chamado `.yml` contendo:\n\n

**Comment by sudo-give-me-coffee** [comment]
@daigoasuka sugestão de ação com o nome `dfdfdf.yml` contendo:\n\n```yml\n\nname: dfdfdf\npattern: sdfsdf\ntype: command\nicon: org.xfce.terminalemulator\nurl: sdsdsd

**Comment by sudo-give-me-coffee** [comment]
@daigoasuka sugestão de ação com o nome `dfdfdf.yml` <br/> contendo:\n\n```yml\n\nname: dfdfdf\npattern: sdfsdf\ntype: command\nicon: org.xfce.terminalemulator\nurl: sdsdsd

**Comment by sudo-give-me-coffee** [comment]
@ daigoasuka sugestão de ação com o nome `dfdfdf.yml` contendo:<br/><br/>

**Comment by sudo-give-me-coffee** [comment]
@ daigoasuka sugestão de ação com o nome `dfdfdf.yml` contendo:<br/><br/>```<br/>```

**Comment by sudo-give-me-coffee** [comment]
@daigo asuka sugestão de ação com o nome `dfdfdf.yml` contendo:

```yaml
name: dfdfdf
pattern: sdfsdf
type: command
icon: org.xfce.terminalemulator
url: sdsdsd
```

**Comment by sudo-give-me-coffee** [comment]
@daigo asuka sugestão de ação: `dfdfdf.yml` contendo:

```yaml
name: dfdfdf
pattern: sdfsdf
type: command
icon: org.xfce.terminalemulator
url: sdsdsd
```
